### PR TITLE
Add missing `sexplib0` build dependency to README

### PR DESCRIPTION
**Pull request by mattaudesse**
```bash
--> opam switch create janestreet-base 4.07.1 # Output elided
--> opam install jbuilder                     # Output elided

--> make
jbuilder build @install
File "src/jbuild", line 29, characters 4-12:
29 |     sexplib0
         ^^^^^^^^
Error: Library "sexplib0" not found.
Hint: try: dune external-lib-deps --missing @install
*** Error code 1

Stop.
make: stopped in /apps/apps/janestreet/base

--> opam install sexplib0 # Output elided

--> make # Now it succeeds
jbuilder build @install
```

Thanks!

Signed-off-by: Matt Audesse <matt@mattaudesse.com>

### CODE REVIEW

**Comment by mattaudesse** [comment]
I just noticed there was a merge conflict introduced by c8f6acf - I've fixed it now.

**Comment by XVilka** [comment]
Seems still valid note: https://github.com/janestreet/base/blob/master/src/dune#L11

**Comment by hhugo** [comment]
This was temporarily reverted but should reappear soon.

**Comment by hhugo** [comment]
cc @xclerc

**Pull request merged**
