### PR TITLE
squared exponentiation for apply_n_times

### PR DESCRIPTION
**Pull request by ytrellu**
That's a complexity improvement to the apply_n_times function; essentially generalizing the exponentiation by squaring trick: https://en.wikipedia.org/wiki/Exponentiation_by_squaring

### CODE REVIEW

**Comment by bcc32** [comment]
I think this doesn't provide any performance benefit, because it still applies the function `f` n times.  I think the only reason exponentiation-by-squaring works to reduce complexity is because the cost of multiplying some number by `x*x` is the same as multiplying by `x`, if you store `x*x` in a variable.  That logic doesn't hold true for function application, because `compose f f` does twice as much work as `f`.

**Comment by ytrellu** [comment]
I would agree if the arguments were not evaluated each time, but that's the case here. Let me produce a core_bench test, at least in terms of memory the improvement should be shown

**Comment by ytrellu** [comment]
Here is one test:
```ocaml
open Core
open Core_bench

let compose f g x = f (g x)

let rec apply_n_times ~n f =
  if n <= 0 then (fun x -> x) else compose f (apply_n_times ~n:(n -1) f )

let rec sq_exp ~n g x =
  if n <= 0 then x
  else if n = 1 then g x
  else if n mod 2 = 0 then sq_exp ~n:(n / 2) (compose g g) x
  else sq_exp ~n:(n - 1) g (g x)

let h x = [| x.(0) - 4 * x.(2); x.(1) * x.(1) - x.(2); - x.(0) |]

let test_base () = apply_n_times ~n:12345 h [| 1; 0; 1 |]
let test_sq_exp () = sq_exp ~n:12345 h [| 1; 0; 1 |]

let () = ["base", test_base; "sq_exp", test_sq_exp]
         |> List.map ~f:(fun (name, t) -> Bench.Test.create ~name t)
         |> Bench.make_command
         |> Command.run
```

```
opam@e273075b05b7:~/ws$ corebuild -pkg core_bench test.byte
Finished, 3 targets (0 cached) in 00:00:01.
opam@e273075b05b7:~/ws$ ./test.byte
Estimated testing time 20s (2 benchmarks x 10s). Change using '-quota'.
┌────────┬────────────┬──────────┬────────────┬────────────┬────────────┐
│ Name   │   Time/Run │  mWd/Run │   mjWd/Run │   Prom/Run │ Percentage │
├────────┼────────────┼──────────┼────────────┼────────────┼────────────┤
│ base   │ 1_241.75us │ 111.11kw │ 20_884.51w │ 20_884.51w │    100.00% │
│ sq_exp │   820.31us │  49.45kw │     13.75w │     13.75w │     66.06% │
└────────┴────────────┴──────────┴────────────┴────────────┴────────────┘
```

**Comment by bcc32** [comment]
No worries.  This is an interesting result nevertheless, and thanks for bringing it up.  I think what's happening is that your `apply_n_times` just allocates a whole lot more than `sq_exp` because the chain of closures is `O(n)` long, whereas the `sq_exp` closure chain is `O(log n)` long.  It's allocating major words each run, and my guess would be that the performance difference comes down to the number of times each function calls the garbage collector.

`Base.Fn.apply_n_times` only allocates one closure so it doesn't suffer from this.

**Comment by ytrellu** [comment]
Hi again @bcc32,

> because the chain of closures is O(n)

Indeed, thanks ,I was comparing against an `apply_n_times` which was not tail-recursive

So I looked at it some more; and so to clarify what I meant and what still bugs me:

I can't think of a meaningful example where an `'a -> 'a` cannot be represented by a value. I corrected the benchmarking code and it should examplify what I mean, using a matrix (value) to represent a linear map (function).

Also maybe for context, `apply_n_times` is implemented in the semigroup class in the Haskell library (the squared exponentiation version); I liked it that the implementation was made available at such an abstraction level, and therefore wondered where its place was in ocaml.

```ocaml
open Core
open Core_bench

(* matrix operations *)
let dot x y = Array.(map2_exn x y ~f:( * ) |> reduce_exn ~f:( + ))
let mat_apply mat x = Array.map ~f:(dot x) mat
let mat_compose x y = Array.(map ~f:(mat_apply (transpose_exn x)) y)

let rec apply_n_times ~n apply compose f x =
  if n <= 0 then x
  else if n = 1 then apply f x
  else if n mod 2 = 0 then apply_n_times ~n:(n / 2) apply compose (compose f f) x
  else apply_n_times ~n:(n - 1) apply compose f (apply f x)

let h = [| [| 1; 1|]; [| 0; 1|]|]
let fun_of_h x = [| x.(0) + x.(1); x.(1)|]
let n = 12345
let arg = [|2; 0|]

let () = assert ((Fn.apply_n_times ~n fun_of_h arg).(0) = (apply_n_times ~n mat_apply mat_compose h arg).(0))

let () = [
  "base", (fun () -> Fn.apply_n_times ~n fun_of_h arg);
  "sq_exp_fun", (fun () -> apply_n_times ~n (fun f x -> f x) Fn.compose fun_of_h arg);
  "sq_exp_val", (fun () -> apply_n_times ~n mat_apply mat_compose h arg)
]
  |> List.map ~f:(fun (name, t) -> Bench.Test.create ~name t)
  |> Bench.make_command
  |> Command.run
```
```bash
opam@7099904a2aa4:~/ws$ corebuild -pkg core_bench test.native
Finished, 4 targets (0 cached) in 00:00:01.
opam@7099904a2aa4:~/ws$ ./test.native
Estimated testing time 30s (3 benchmarks x 10s). Change using '-quota'.
┌────────────┬──────────┬─────────┬──────────┬──────────┬────────────┐
│ Name       │ Time/Run │ mWd/Run │ mjWd/Run │ Prom/Run │ Percentage │
├────────────┼──────────┼─────────┼──────────┼──────────┼────────────┤
│ base       │  31.54us │ 37.04kw │    0.42w │    0.42w │     52.98% │
│ sq_exp_fun │  59.53us │ 37.18kw │   18.04w │   18.04w │    100.00% │
│ sq_exp_val │   3.82us │  1.45kw │    0.16w │    0.16w │      6.42% │
└────────────┴──────────┴─────────┴──────────┴──────────┴────────────┘
```

**Comment by bcc32** [comment]
> I can't think of a meaningful example where an `'a -> 'a` cannot be represented by a value. I corrected the benchmarking code and it should examplify what I mean, using a matrix (value) to represent a linear map (function).
> 

I'm not sure I understand what you're asking with this example.  In general, there is no technique for taking some arbitrary `'a -> 'a` and composing it with itself without creating a closure.  That is to say, `Base.Fn.apply_n_times`, given the signature it needs to satisfy, could not use any "compose" operation other than `Fn.compose`, which creates a closure.  Unless you meant that `Fn.apply_n_times` should gain two more parameters: `apply` and `compose`, and should work on values representing "operations" but which aren't normal OCaml functions.  I think that is kind of outside the scope of `Base.Fn`.

> Also maybe for context, `apply_n_times` is implemented in the semigroup class in the Haskell library (the squared exponentiation version); I liked it that the implementation was made available at such an abstraction level, and therefore wondered where its place was in ocaml.

Can you point me to this?  I'm not very familiar with Haskell.  I looked at the [semigroup documentation](https://hackage.haskell.org/package/base-4.14.1.0/docs/Data-Semigroup.html) but wasn't able to find a corresponding instance for arbitrary `a -> a`.

**Comment by ytrellu** [comment]
Agreed yes, my point is then that the signature for `Base.Fn.apply_n_times` is somewhat misleading. Should you find yourself in a situation where you think of using it, you should have defined a meaningful `compose` beforehand in order to avoid the generation of O(n) closures.

But yes, agreed, should the squared exponentiation be implemented somewhere, `Base.Fn` is not the right candidate module. It is the closest thing to a `Semigroup` or `Monoid` module, and that's why I played around with it. I was not fully understanding closures (and thanks for bringing it).

The Haskell implementation I was referring to is [here](https://hackage.haskell.org/package/base-4.14.1.0/docs/src/Data.Semigroup.Internal.html#stimesDefault). It is not an instance for arbitrary `a -> a`, only for those with a defined `compose`, hence its belonging to the `Data.Semigroup`.

**Comment by bcc32** [comment]
> 
> 
> Agreed yes, my point is then that the signature for `Base.Fn.apply_n_times` is somewhat misleading. Should you find yourself in a situation where you think of using it, you should have defined a meaningful `compose` beforehand in order to avoid the generation of O(n) closures.
> 

I don't think I agree with your conclusion.  The current implementation of `Base.Fn.apply_n_times` does not generate `O(n)` closures; you are thinking of the squared-exponentiation implementation.  `Base.Fn.apply_n_times` is a straightforward loop; no real work is done, except for closing over the value of `n`, until you supply all of the arguments.

> But yes, agreed, should the squared exponentiation be implemented somewhere, `Base.Fn` is not the right candidate module. It is the closest thing to a `Semigroup` or `Monoid` module, and that's why I played around with it. I was not fully understanding closures (and thanks for bringing it).
> 
> The Haskell implementation I was referring to is [here](https://hackage.haskell.org/package/base-4.14.1.0/docs/src/Data.Semigroup.Internal.html#stimesDefault). It is not an instance for arbitrary `a -> a`, only for those with a defined `compose`, hence its belonging to the `Data.Semigroup`. To keep in mind here is the 'functor' between a semigroup `b` and `a -> a`, that exists for each semigroup action `apply: b -> a -> a`.

Thanks for the link.

**Pull request closed without merging**
