### PR TITLE
Add Bytes.{map, mapi, fold, foldi, to_array}

### PR DESCRIPTION
**Pull request by XVilka**
Aim to fix https://github.com/janestreet/base/issues/50

### CODE REVIEW

**Comment by diml** [comment]
Thanks, I imported the patch in our internal review system

**Comment by XVilka** [comment]
So? Any decision yet?

**Comment by diml** [comment]
I got an error from the CI, but I haven't investigated yet. Here is the error I get:

```
File "bytes.ml", line 72, characters 29-30:
Error: This expression has type int but an expression was expected of type t
- exit lib/base/src base__Bytes.cmo, 43ms, exited with code 2
```

This is with 4.06.1. Were you able to build the code?

**Comment by diml** [comment]
I don't remember the details, but it's possible that the `=` in this module is string equality. Could you try using `Int.equal`?

**Comment by XVilka** [comment]
Fixed and tested locally now, thanks for the hint!

**Comment by diml** [comment]
No problem, I updated our internal feature. I'll let you know how it goes

**Comment by seliopou** [comment]
Do you have a particular use of these functions in mind, or is this just for "completeness"?

**Comment by XVilka** [comment]
So? Was there any decision yet?

**Comment by seliopou** [comment]
Hey, sorry this fell off my radar.

Did you by any chance come across [these casting functions](https://github.com/janestreet/base/blob/master/src/bytes.mli#L98-L185) while you were looking at the `Bytes` module? They're there specifically for expert users that need something along the lines of what you're looking for.

I ask because this change could be the start of a slippery slope to having the `Bytes` module support the entirety of the `String` module, which would introduce a lot of duplication in their implementations. The casts I mentioned above was how we were hoping to address that issue.

But, not totally opposed to including these operations. Though of all of them, the `fold`s seem the most out-of-place.

**Comment by XVilka** [comment]
@seliopou yes, I am aware of them and use them where appropriate in my code. I am still not sure what is the best way do deal with this. On the one hand casting back and forth every time feels dirty, on the other hand - maybe we can functorize the whole Bytes & Strings thing and code only a differences instead?

**Comment by xclerc** [comment]
Relased, see commit https://github.com/janestreet/base/commit/c76eacebcb41c072005cfbfd3aa2eb0ceb93f933.

**Pull request closed without merging**
